export const ADD_SHOP_LIST_DATA_REQUIEST = "ADD_SHOP_LIST_DATA_REQUIEST"
export const ADD_SHOP_LIST_DATA_SUCCESS = "ADD_SHOP_LIST_DATA_SUCCESS"
export const ADD_SHOP_LIST_DATA_FAIL = "ADD_SHOP_LIST_DATA_FAIL"

export const SHOW_SHOPS_LIST_DATA_REQUIEST = "SHOW_SHOPS_LIST_DATA_REQUIEST"
export const SHOW_SHOPS_LIST_DATA_SUCCESS = "SHOW_SHOPS_LIST_DATA_SUCCESS"
export const SHOW_SHOPS_LIST_DATA_FAIL = "SHOW_SHOPS_LIST_DATA_FAIL"

export const DELETE_SHOPS_LIST_DATA_REQUIEST = "DELETE_SHOPS_LIST_DATA_REQUIEST"
export const DELETE_SHOPS_LIST_DATA_SUCCESS = "DELETE_SHOPS_LIST_DATA_SUCCESS"
export const DELETE_SHOPS_LIST_DATA_FAIL = "DELETE_SHOPS_LIST_DATA_FAIL"

export const UPDATE_SHOPS_LIST_DATA_REQUIEST = "UPDATE_SHOPS_LIST_DATA_REQUIEST"
export const UPDATE_SHOPS_LIST_DATA_SUCCESS = "UPDATE_SHOPS_LIST_DATA_SUCCESS"
export const UPDATE_SHOPS_LIST_DATA_FAIL = "UPDATE_SHOPS_LIST_DATA_FAIL"
